# Generated by Django 2.0.1 on 2018-07-12 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(max_length=50, verbose_name='资产编号')),
                ('zcname', models.CharField(max_length=16, verbose_name='资产名称')),
                ('guige', models.CharField(default='请填写详细型号信息', max_length=300, verbose_name='规格型号')),
                ('zcconditons', models.CharField(default='正常', max_length=8, verbose_name='资产状态')),
                ('cgdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='购置日期')),
                ('guanlibm', models.CharField(default='行政管理中心', max_length=12, verbose_name='管理部门')),
                ('guanliadmin', models.CharField(default='李秀娜', max_length=10, verbose_name='管理员工')),
                ('cfangwz', models.CharField(default='E谷办公区', max_length=10, verbose_name='存放位置')),
                ('shiyongzk', models.CharField(max_length=10, verbose_name='使用状况')),
                ('zcdanwei', models.CharField(default='台', max_length=10, verbose_name='资产单位')),
                ('zcjz', models.FloatField(default=0, verbose_name='资产净值')),
                ('shiyongbm', models.CharField(max_length=16, verbose_name='领用部门')),
                ('shiyongyg', models.CharField(max_length=12, verbose_name='领用员工')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '资产列表',
                'verbose_name_plural': '资产列表',
            },
        ),
    ]
